version: "3"

services:
  nginxauth:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mylocal
  auth1:
    build: .
    networks:
      - mylocal
  auth2:
    build: .
    networks:
      - mylocal
  auth3:
    build: .
    networks:
      - mylocal
networks:
  mylocal:
    external: true