version: "3"

services:
  nginxauth:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mylocal
  auth:
    build: .
    networks:
      - mylocal
    deploy:
      mode: replicated
      replicas: 3

networks:
  mylocal:
    external: true